### ISSUE TITLE
Cannot compile with vala 0.48.15

### ISSUE THREAD

**Issue by pkgzm** [valum-framework/vsgi#5]
with valac 0.48.15, during compilation I get the following messages:

...
../../../../../../src/web-apps/valum-framework/vsgi/src/vsgi-request.vala:382.5-382.44: error: Assignment: Cannot convert from `GLib.HashTable<weak string,weak string>' to `GLib.HashTable<string,string>?'
				_query = Soup.Form.decode (query_string);
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../../src/web-apps/valum-framework/vsgi/src/vsgi-request.vala:390.5-390.65: error: Assignment: Cannot convert from `GLib.HashTable<weak string,weak string>' to `GLib.HashTable<string,string>?'
				_query = Soup.Form.decode (path_translated.split ("?", 2)[1]);
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../../src/web-apps/valum-framework/vsgi/src/vsgi-request.vala:398.5-398.61: error: Assignment: Cannot convert from `GLib.HashTable<weak string,weak string>' to `GLib.HashTable<string,string>?'
				_query = Soup.Form.decode (request_uri.split ("?", 2)[1]);
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../../src/web-apps/valum-framework/vsgi/src/vsgi-request.vala:434.5-434.82: error: Assignment: Cannot convert from `GLib.HashTable<weak string,weak string>?' to `GLib.HashTable<string,string>?'
				_query = uri.get_query () == null ? null : Soup.Form.decode (uri.get_query ());
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 4 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.

**Comment by arteymix** [comment]
It appears that the libsoup API has been slightly altered. I have the same compiler version, so I'll make the fixes.

**Comment by arteymix** [comment]
It seems I already addressed this issue here: https://github.com/valum-framework/vsgi/commit/4c0318d3a2a7f47158ae220cae07c72af469d2e1

Which release are you using?

**Comment by pkgzm** [comment]
I agree with you: I was in an old release, and you already fixed the issue.
The issue can be closed.

Sorry for the noise...
